doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        types:
            custom_id: App\Infrastructure\Common\Orm\CustomType\IdCustomType
            specie_name: App\Infrastructure\Pokemon\Orm\Doctrine\CustomType\SpecieNameCustomType
            elemental_types: App\Infrastructure\Pokemon\Orm\Doctrine\CustomType\ElementalTypeCollectionCustomType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Pokemon:
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Pokemon/Orm/Doctrine/Mapping'
                prefix: 'App\Domain\Pokemon\Entity'

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
