version: '3.1'
services:
  db:
    image: mysql:8.2
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - 3306:3306
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: Us3r
      MYSQL_PASSWORD: S0m3P4ssw0rd
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: storage
  adminer:
    image: adminer:4.8.1
    ports:
      - 8080:8080