services:
  # Tactician #
  App\Infrastructure\Pokemon\Bus\Tactician\Mapping\CommandToHandlerMap:

  App\Infrastructure\Common\Bus\Tactician\Middleware\CommandHandlerMiddlewareFactory:
    arguments:
      - '@service_container'
      - [
          '@App\Infrastructure\Pokemon\Bus\Tactician\Mapping\CommandToHandlerMap'
      ]

  League\Tactician\Handler\CommandHandlerMiddleware:
    factory:
      - '@App\Infrastructure\Common\Bus\Tactician\Middleware\CommandHandlerMiddlewareFactory'
      - make

  League\Tactician\Doctrine\ORM\TransactionMiddleware:
    arguments:
      - '@doctrine.orm.entity_manager'

  League\Tactician\CommandBus:
    arguments:
      - [
          '@League\Tactician\Doctrine\ORM\TransactionMiddleware',
          '@League\Tactician\Handler\CommandHandlerMiddleware'
      ]

  # Doctrine #
  App\Infrastructure\Pokemon\Repository\DoctrineSpecieRepository:
    arguments:
      - '@doctrine'

  # UI / API #
  App\Ui\Api\Pokemon\Controller\CreateSpecieController:
    tags: [ 'controller.service_arguments' ]
    arguments:
      - '@App\Ui\Api\Pokemon\Converter\RequestToCreateSpecieCommandConverter'
      - '@League\Tactician\CommandBus'

  App\Ui\Api\Pokemon\Converter\RequestToCreateSpecieCommandConverter:

  # Application #
  App\Application\Pokemon\Command\CreateSpecie\CreateSpecieHandler:
    public: true
    arguments:
      - '@App\Infrastructure\Pokemon\Repository\DoctrineSpecieRepository'