services:
  App\Ui\Api\Pokemon\Controller\CreateSpecieController:
    tags: [ 'controller.service_arguments' ]
    arguments:
      - '@App\Ui\Api\Pokemon\Converter\RequestToCreateSpecieCommandConverter'
      - '@App\Application\Pokemon\Command\CreateSpecie\CreateSpecieHandler'

  App\Ui\Api\Pokemon\Converter\RequestToCreateSpecieCommandConverter:

  App\Application\Pokemon\Command\CreateSpecie\CreateSpecieHandler:
    arguments:
      - '@App\Infrastructure\Pokemon\Repository\TmpSpecieRepository'

  App\Infrastructure\Pokemon\Repository\TmpSpecieRepository: